// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Color.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SOULS.Color {

  /// <summary>Holder for reflection information generated from Color.proto</summary>
  public static partial class ColorReflection {

    #region Descriptor
    /// <summary>File descriptor for Color.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ColorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtDb2xvci5wcm90bxILU09VTFMuQ29sb3IilQEKBUNvbG9yEgkKAVIYASAB",
            "KAUSCQoBRxgCIAEoBRIJCgFCGAMgASgFEgkKAUEYBCABKAUSFAoMSXNLbm93",
            "bkNvbG9yGAUgASgIEg8KB0lzRW1wdHkYBiABKAgSFAoMSXNOYW1lZENvbG9y",
            "GAcgASgIEhUKDUlzU3lzdGVtQ29sb3IYCCABKAgSDAoETmFtZRgJIAEoCWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SOULS.Color.Color), global::SOULS.Color.Color.Parser, new[]{ "R", "G", "B", "A", "IsKnownColor", "IsEmpty", "IsNamedColor", "IsSystemColor", "Name" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Color : pb::IMessage<Color> {
    private static readonly pb::MessageParser<Color> _parser = new pb::MessageParser<Color>(() => new Color());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Color> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SOULS.Color.ColorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Color() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Color(Color other) : this() {
      r_ = other.r_;
      g_ = other.g_;
      b_ = other.b_;
      a_ = other.a_;
      isKnownColor_ = other.isKnownColor_;
      isEmpty_ = other.isEmpty_;
      isNamedColor_ = other.isNamedColor_;
      isSystemColor_ = other.isSystemColor_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Color Clone() {
      return new Color(this);
    }

    /// <summary>Field number for the "R" field.</summary>
    public const int RFieldNumber = 1;
    private int r_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "G" field.</summary>
    public const int GFieldNumber = 2;
    private int g_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int G {
      get { return g_; }
      set {
        g_ = value;
      }
    }

    /// <summary>Field number for the "B" field.</summary>
    public const int BFieldNumber = 3;
    private int b_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int B {
      get { return b_; }
      set {
        b_ = value;
      }
    }

    /// <summary>Field number for the "A" field.</summary>
    public const int AFieldNumber = 4;
    private int a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    /// <summary>Field number for the "IsKnownColor" field.</summary>
    public const int IsKnownColorFieldNumber = 5;
    private bool isKnownColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsKnownColor {
      get { return isKnownColor_; }
      set {
        isKnownColor_ = value;
      }
    }

    /// <summary>Field number for the "IsEmpty" field.</summary>
    public const int IsEmptyFieldNumber = 6;
    private bool isEmpty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsEmpty {
      get { return isEmpty_; }
      set {
        isEmpty_ = value;
      }
    }

    /// <summary>Field number for the "IsNamedColor" field.</summary>
    public const int IsNamedColorFieldNumber = 7;
    private bool isNamedColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsNamedColor {
      get { return isNamedColor_; }
      set {
        isNamedColor_ = value;
      }
    }

    /// <summary>Field number for the "IsSystemColor" field.</summary>
    public const int IsSystemColorFieldNumber = 8;
    private bool isSystemColor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSystemColor {
      get { return isSystemColor_; }
      set {
        isSystemColor_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 9;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Color);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Color other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (R != other.R) return false;
      if (G != other.G) return false;
      if (B != other.B) return false;
      if (A != other.A) return false;
      if (IsKnownColor != other.IsKnownColor) return false;
      if (IsEmpty != other.IsEmpty) return false;
      if (IsNamedColor != other.IsNamedColor) return false;
      if (IsSystemColor != other.IsSystemColor) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (R != 0) hash ^= R.GetHashCode();
      if (G != 0) hash ^= G.GetHashCode();
      if (B != 0) hash ^= B.GetHashCode();
      if (A != 0) hash ^= A.GetHashCode();
      if (IsKnownColor != false) hash ^= IsKnownColor.GetHashCode();
      if (IsEmpty != false) hash ^= IsEmpty.GetHashCode();
      if (IsNamedColor != false) hash ^= IsNamedColor.GetHashCode();
      if (IsSystemColor != false) hash ^= IsSystemColor.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(R);
      }
      if (G != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(G);
      }
      if (B != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(B);
      }
      if (A != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(A);
      }
      if (IsKnownColor != false) {
        output.WriteRawTag(40);
        output.WriteBool(IsKnownColor);
      }
      if (IsEmpty != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsEmpty);
      }
      if (IsNamedColor != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsNamedColor);
      }
      if (IsSystemColor != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsSystemColor);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(R);
      }
      if (G != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(G);
      }
      if (B != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(B);
      }
      if (A != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(A);
      }
      if (IsKnownColor != false) {
        size += 1 + 1;
      }
      if (IsEmpty != false) {
        size += 1 + 1;
      }
      if (IsNamedColor != false) {
        size += 1 + 1;
      }
      if (IsSystemColor != false) {
        size += 1 + 1;
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Color other) {
      if (other == null) {
        return;
      }
      if (other.R != 0) {
        R = other.R;
      }
      if (other.G != 0) {
        G = other.G;
      }
      if (other.B != 0) {
        B = other.B;
      }
      if (other.A != 0) {
        A = other.A;
      }
      if (other.IsKnownColor != false) {
        IsKnownColor = other.IsKnownColor;
      }
      if (other.IsEmpty != false) {
        IsEmpty = other.IsEmpty;
      }
      if (other.IsNamedColor != false) {
        IsNamedColor = other.IsNamedColor;
      }
      if (other.IsSystemColor != false) {
        IsSystemColor = other.IsSystemColor;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            R = input.ReadInt32();
            break;
          }
          case 16: {
            G = input.ReadInt32();
            break;
          }
          case 24: {
            B = input.ReadInt32();
            break;
          }
          case 32: {
            A = input.ReadInt32();
            break;
          }
          case 40: {
            IsKnownColor = input.ReadBool();
            break;
          }
          case 48: {
            IsEmpty = input.ReadBool();
            break;
          }
          case 56: {
            IsNamedColor = input.ReadBool();
            break;
          }
          case 64: {
            IsSystemColor = input.ReadBool();
            break;
          }
          case 74: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
